#pragma once

#include <QLabel>
#include <QPlainTextEdit>
#include <QTextEdit>
#include <QRegularExpression>
#include <unordered_set>
#include <QString>
#include <string>
#include <QWidget>
#include <vector>
#include <QAbstractButton>
#include <QPushButton>
#include <QCoreApplication>
#include <QGuiApplication>
#include <QApplication>
#include <QMainWindow>
#include <iostream>
#include <fstream>
#include <QFileDialog>
#include <QTextBrowser>